[package]
authors      = ["CallOrRet <callorret@icloud.com>"]
categories   = ["command-line-utilities", "development-tools::cargo-plugins"]
default-run  = "cargo-reorder"
description  = "Reorder top-level items in Rust source files following community style"
edition      = "2024"
exclude      = ["rust-toolchain.toml"]
keywords     = ["cargo", "reorder", "format", "items", "imports"]
license      = "Apache-2.0"
name         = "cargo-reorder"
readme       = "README.md"
repository   = "https://github.com/CallOrRet/cargo-reorder"
rust-version = "1.85"
version      = "0.3.0"

[[bin]]
name = "cargo-reorder"
path = "src/main.rs"

[lib]
name = "cargo_reorder"
path = "src/lib.rs"

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[package.metadata.binstall]
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.{ archive-format }"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-fmt = "zip"

[dependencies]
anyhow      = { version = "1" }
clap        = { version = "4", features = ["derive"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
serde_json  = { version = "1" }
similar     = { version = "3" }
syn         = { version = "2", features = ["full", "extra-traits", "parsing", "printing", "visit"] }

[dev-dependencies]
criterion         = { version = "0.5", default-features = false, features = ["cargo_bench_support"] }
pretty_assertions = { version = "1" }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.15", features = ["protobuf-codec", "criterion"] }

[[bench]]
harness = false
name    = "reorder"

[lints.clippy]
all = { level = "deny", priority = -1 }

[profile.bench]
debug = true
